<?php
require_once '../classes/Auth.php';
require_once '../classes/Drug.php';
require_once '../classes/Order.php';
require_once '../classes/Prescription.php';
require_once '../classes/AIService.php';

$auth = new Auth();
$auth->requireRole('admin');

$error = '';
$report_data = null;

// Get export parameters
$report_type = $_GET['type'] ?? '';
$format = $_GET['format'] ?? 'csv';
$date_from = $_GET['date_from'] ?? '';
$date_to = $_GET['date_to'] ?? '';

if (!$report_type) {
    die('Report type is required');
}

// Initialize classes
$drug = new Drug();
$order = new Order();
$prescription = new Prescription();
$ai_service = new AIService();

// Get report data
switch ($report_type) {
    case 'sales_report':
        $report_data = $order->getSalesReport($date_from, $date_to);
        $filename = "sales_report_" . date('Y-m-d') . ".$format";
        break;
    case 'inventory_report':
        $report_data = $drug->getInventoryReport();
        $filename = "inventory_report_" . date('Y-m-d') . ".$format";
        break;
    case 'prescription_report':
        $report_data = $prescription->getPrescriptionReport($date_from, $date_to);
        $filename = "prescription_report_" . date('Y-m-d') . ".$format";
        break;
    case 'ai_usage_report':
        $report_data = $ai_service->getAIUsageReport($date_from, $date_to);
        $filename = "ai_usage_report_" . date('Y-m-d') . ".$format";
        break;
    case 'user_activity_report':
        $report_data = $auth->getUserActivityReport($date_from, $date_to);
        $filename = "user_activity_report_" . date('Y-m-d') . ".$format";
        break;
    default:
        die('Invalid report type');
}

if (!$report_data || empty($report_data)) {
    die('No data available for export');
}

// Export based on format
switch ($format) {
    case 'csv':
        exportCSV($report_data, $filename, $report_type);
        break;
    case 'pdf':
        exportPDF($report_data, $filename, $report_type);
        break;
    case 'excel':
        exportExcel($report_data, $filename, $report_type);
        break;
    default:
        die('Unsupported export format');
}

function exportCSV($data, $filename, $report_type) {
    // Set headers for CSV download
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    // Create output stream
    $output = fopen('php://output', 'w');
    
    // Add BOM for UTF-8 encoding (helps with Excel compatibility)
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    // Add report header
    fputcsv($output, ['Sky Pharmacy - ' . ucwords(str_replace('_', ' ', $report_type)) . ' Report']);
    fputcsv($output, ['Generated on: ' . date('F d, Y \a\t g:i A')]);
    fputcsv($output, ['Report Type: ' . ucwords(str_replace('_', ' ', $report_type))]);
    fputcsv($output, ['Data Range: ' . (isset($_GET['date_from']) && $_GET['date_from'] ? 'From ' . $_GET['date_from'] : 'All Time') . 
                      (isset($_GET['date_to']) && $_GET['date_to'] ? ' To ' . $_GET['date_to'] : '')]);
    fputcsv($output, []); // Empty row
    
    // Add column headers
    if (!empty($data)) {
        $headers = array_keys($data[0]);
        // Format headers for better readability
        $formatted_headers = array_map(function($header) {
            return ucwords(str_replace('_', ' ', $header));
        }, $headers);
        fputcsv($output, $formatted_headers);
        
        // Add data rows
        foreach ($data as $row) {
            // Format data for better CSV output
            $formatted_row = array_map(function($value) {
                // Handle special characters and formatting
                if (is_numeric($value)) {
                    return $value;
                } elseif (strpos($value, ',') !== false || strpos($value, '"') !== false || strpos($value, "\n") !== false) {
                    return '"' . str_replace('"', '""', $value) . '"';
                } else {
                    return $value;
                }
            }, $row);
            fputcsv($output, $formatted_row);
        }
        
        // Add summary row
        fputcsv($output, []); // Empty row
        fputcsv($output, ['Total Records: ' . count($data)]);
        fputcsv($output, ['Report generated by: System Administrator']);
    }
    
    fclose($output);
    exit;
}

function exportPDF($data, $filename, $report_type) {
    // For PDF export, we'll create a simple HTML-based PDF
    // In a production environment, you might want to use a library like TCPDF or FPDF
    
    $html = generatePDFHTML($data, $report_type);
    
    // Set headers for PDF download
    header('Content-Type: text/html');
    header('Content-Disposition: attachment; filename="' . $filename . '.html"');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    // Output HTML that can be printed to PDF using browser print function
    echo $html;
    exit;
}

function exportExcel($data, $filename, $report_type) {
    // For Excel export, we'll create a CSV with Excel-compatible formatting
    // In a production environment, you might want to use PHPSpreadsheet
    
    // Set headers for Excel download
    header('Content-Type: application/vnd.ms-excel; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    // Create output stream
    $output = fopen('php://output', 'w');
    
    // Add BOM for UTF-8 encoding (helps with Excel compatibility)
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    // Add report header with Excel formatting
    fputcsv($output, ['Sky Pharmacy - ' . ucwords(str_replace('_', ' ', $report_type)) . ' Report']);
    fputcsv($output, ['Generated on: ' . date('F d, Y \a\t g:i A')]);
    fputcsv($output, ['Report Type: ' . ucwords(str_replace('_', ' ', $report_type))]);
    fputcsv($output, ['Data Range: ' . (isset($_GET['date_from']) && $_GET['date_from'] ? 'From ' . $_GET['date_from'] : 'All Time') . 
                      (isset($_GET['date_to']) && $_GET['date_to'] ? ' To ' . $_GET['date_to'] : '')]);
    fputcsv($output, []); // Empty row
    
    // Add column headers
    if (!empty($data)) {
        $headers = array_keys($data[0]);
        // Format headers for better readability
        $formatted_headers = array_map(function($header) {
            return ucwords(str_replace('_', ' ', $header));
        }, $headers);
        fputcsv($output, $formatted_headers);
        
        // Add data rows with Excel-friendly formatting
        foreach ($data as $row) {
            // Format data for better Excel output
            $formatted_row = array_map(function($value) {
                // Handle special characters and formatting for Excel
                if (is_numeric($value)) {
                    return $value;
                } elseif (strpos($value, ',') !== false || strpos($value, '"') !== false || strpos($value, "\n") !== false) {
                    return '"' . str_replace('"', '""', $value) . '"';
                } else {
                    return $value;
                }
            }, $row);
            fputcsv($output, $formatted_row);
        }
        
        // Add summary section
        fputcsv($output, []); // Empty row
        fputcsv($output, ['Report Summary']);
        fputcsv($output, ['Total Records', count($data)]);
        fputcsv($output, ['Report Type', ucwords(str_replace('_', ' ', $report_type))]);
        fputcsv($output, ['Generated By', 'System Administrator']);
        fputcsv($output, ['Generated Date', date('F d, Y \a\t g:i A')]);
    }
    
    fclose($output);
    exit;
}

function generatePDFHTML($data, $report_type) {
    $html = '
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Sky Pharmacy - ' . ucwords(str_replace('_', ' ', $report_type)) . ' Report</title>
        <style>
            @media print {
                body { margin: 0; padding: 20px; }
                .no-print { display: none; }
            }
            body { 
                font-family: Arial, sans-serif; 
                margin: 20px; 
                line-height: 1.6;
                color: #333;
            }
            .header { 
                text-align: center; 
                margin-bottom: 30px; 
                border-bottom: 2px solid #667eea; 
                padding-bottom: 15px; 
            }
            .report-title { 
                font-size: 28px; 
                font-weight: bold; 
                color: #667eea; 
                margin-bottom: 5px;
            }
            .report-subtitle {
                font-size: 20px;
                color: #333;
                margin-bottom: 10px;
            }
            .report-date { 
                font-size: 14px; 
                color: #666; 
                margin-top: 5px; 
            }
            .report-info {
                background-color: #f8f9fa;
                padding: 15px;
                border-radius: 5px;
                margin-bottom: 20px;
                border-left: 4px solid #667eea;
            }
            table { 
                width: 100%; 
                border-collapse: collapse; 
                margin-top: 20px; 
                font-size: 12px;
            }
            th, td { 
                border: 1px solid #ddd; 
                padding: 10px; 
                text-align: left; 
                vertical-align: top;
            }
            th { 
                background-color: #667eea; 
                color: white;
                font-weight: bold; 
                text-transform: uppercase;
                font-size: 11px;
            }
            tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            .summary { 
                margin-top: 30px; 
                padding: 20px; 
                background-color: #f8f9fa; 
                border-radius: 8px;
                border: 1px solid #e9ecef;
            }
            .summary h3 {
                color: #667eea;
                margin-top: 0;
                border-bottom: 1px solid #dee2e6;
                padding-bottom: 10px;
            }
            .summary-stats {
                display: flex;
                justify-content: space-around;
                margin-top: 15px;
            }
            .stat-item {
                text-align: center;
                padding: 10px;
            }
            .stat-number {
                font-size: 24px;
                font-weight: bold;
                color: #667eea;
            }
            .stat-label {
                font-size: 12px;
                color: #666;
                text-transform: uppercase;
            }
            .footer {
                margin-top: 30px;
                text-align: center;
                font-size: 12px;
                color: #666;
                border-top: 1px solid #dee2e6;
                padding-top: 15px;
            }
            .print-instructions {
                background-color: #fff3cd;
                border: 1px solid #ffeaa7;
                padding: 15px;
                border-radius: 5px;
                margin-bottom: 20px;
                display: none;
            }
            @media print {
                .print-instructions { display: block; }
            }
        </style>
    </head>
    <body>
        <div class="print-instructions">
            <strong>Print Instructions:</strong> Use Ctrl+P (or Cmd+P on Mac) to print this report. 
            Select "Save as PDF" in the print dialog to save as PDF file.
        </div>
        
        <div class="header">
            <div class="report-title">Sky Pharmacy</div>
            <div class="report-subtitle">' . ucwords(str_replace('_', ' ', $report_type)) . ' Report</div>
            <div class="report-date">Generated on: ' . date('F d, Y \a\t g:i A') . '</div>
        </div>
        
        <div class="report-info">
            <strong>Report Type:</strong> ' . ucwords(str_replace('_', ' ', $report_type)) . '<br>
            <strong>Generated By:</strong> System Administrator<br>
            <strong>Data Range:</strong> ' . (isset($_GET['date_from']) && $_GET['date_from'] ? 'From ' . $_GET['date_from'] : 'All Time') . 
            (isset($_GET['date_to']) && $_GET['date_to'] ? ' To ' . $_GET['date_to'] : '') . '
        </div>
    ';
    
    if (!empty($data)) {
        $html .= '<table>';
        
        // Add headers
        $html .= '<tr>';
        foreach (array_keys($data[0]) as $header) {
            $html .= '<th>' . ucwords(str_replace('_', ' ', $header)) . '</th>';
        }
        $html .= '</tr>';
        
        // Add data rows
        foreach ($data as $row) {
            $html .= '<tr>';
            foreach ($row as $value) {
                $html .= '<td>' . htmlspecialchars($value) . '</td>';
            }
            $html .= '</tr>';
        }
        
        $html .= '</table>';
        
        // Add summary
        $html .= '<div class="summary">';
        $html .= '<h3>Report Summary</h3>';
        $html .= '<div class="summary-stats">';
        $html .= '<div class="stat-item">';
        $html .= '<div class="stat-number">' . count($data) . '</div>';
        $html .= '<div class="stat-label">Total Records</div>';
        $html .= '</div>';
        $html .= '<div class="stat-item">';
        $html .= '<div class="stat-number">' . ucwords(str_replace('_', ' ', $report_type)) . '</div>';
        $html .= '<div class="stat-label">Report Type</div>';
        $html .= '</div>';
        $html .= '<div class="stat-item">';
        $html .= '<div class="stat-number">' . date('M Y') . '</div>';
        $html .= '<div class="stat-label">Generated</div>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</div>';
    } else {
        $html .= '<div class="summary">';
        $html .= '<h3>No Data Available</h3>';
        $html .= '<p>No data was found for the selected criteria. Please try adjusting your date range or report parameters.</p>';
        $html .= '</div>';
    }
    
    $html .= '<div class="footer">';
    $html .= 'Sky Pharmacy Management System<br>';
    $html .= 'This report was generated automatically by the system.<br>';
    $html .= 'For questions or support, please contact the system administrator.';
    $html .= '</div>';
    
    $html .= '</body></html>';
    
    return $html;
}
?> 